### ISSUE TITLE
Parsing repeated fields

### ISSUE THREAD

**Issue by xiaoyong** [ethereon/netscope#1]
Hello @ethereon,

For repeated fields in a prototxt file, we may put the values between a pair of bracket, e.g. `mean_value: [128, 128, 128]`. When trying to visualize it, I got an error:

> Error Encountered
> Line 22, Column 17: Expected "'", "\"", "{", key or number but "[" found.

Is it possible to add support for this syntax? Thanks!

**Comment by ethereon** [comment]
Hi @xiaoyong,

Thanks for reporting this. I've pushed an updated parser that should resolve this issue.

**Comment by xiaoyong** [comment]
Great! Thanks!
