### ISSUE TITLE
Atom Package

### ISSUE THREAD

**Issue by g3n35i5** [ethereon/netscope#19]
Thank you for creating this useful tool, it helps me a lot during my work.
Have you thought about deploying netscope as an Atom package?

**Comment by rlnx** [comment]
@g3n35i5, that's brilliant idea, any help will be appreciated 😄

**Comment by g3n35i5** [comment]
@RuslanIsrafilov, unfortunately, I'm not good enough in Javascript to implement the project, yet. But I am constantly learning and hope to be able to contribute to the project soon.

**Comment by ilyamochalov** [comment]
I am currently working on my company project where we integrate in into VS Code. I will update here if we make something out of it.
