### ISSUE TITLE
Cannot display full of the network

### ISSUE THREAD

**Issue by hizhangp** [ethereon/netscope#3]
Maybe I met a bug that the netscope cannot display full of my network based on RCNN. 

```
http://ethereon.github.io/netscope/#/gist/eed9d59907f8d223e48dc76d48f92694
```

**Comment by ethereon** [comment]
Yup, looks like bug to me. I'll take a look at it this weekend.

**Comment by ethereon** [comment]
Apologies it took a while to get to this. It should be fixed now.
